### ISSUE TITLE
Can't use volume button to change page

### ISSUE THREAD

**Issue by tuanden0** [geometer/fbreader-module-resources#10]
Hi Sir,

I'm using FBreader on my Blackberry Z10. Everything is good, but I can't use volume button to change page. I choose that in the setting but nothing happend. When I pressed volume button in FBreader, the volume control bar appear.

Can you help me sir?
Thank you.

**Comment by geometer** [comment]
I afraid BB devices are too protected. There is no access to volume keys from Android app.
